server:
  port: 8082

spring:
  application:
    name: daily-mutual-fund-nav

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    serverUrl:
      defaultZone: http://localhost:8761/eureka