eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    serverUrl:
      defaultZone: http://localhost:8761/eureka

server:
  port: 8083

spring:
  mvc:
    pathmatch:
      matching-strategy: ant-path-matcher
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: validate
    database-platform: org.hibernate.dialect.H2Dialect
  application:
    name: calculate-networth
  datasource:
    driverClassName: org.h2.Driver
    password: ''
    username: sa
    url: jdbc:h2:mem:calculate
logging:
  level:
    com:
      cognizant: debug
    org:
      springframework: info
      hibernate:
        SQL: trace
        type:
          descriptor:
            sql: trace
  pattern:
    console: '%d{dd-MM-yy} %d{HH:mm:ss.SSS} %-20.20thread %5p %-25.25logger{25} %25M%4L %m%n'

