server:
  port: 9093

spring:
  application:
    name: documentation-service

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    hostname: localhost

swagger:
  config:
    refreshrate: 5000