server:
  port: 8081

spring:
  application:
    name: daily-share-price

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    serverUrl:
      defaultZone: http://localhost:8761/eureka